#:kivy 2.1.0

<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        spacing: 20
        padding: 20
        
        Button:
            text: "olá mundo 1"

        Button:
            text: "olá mundo 2"

        Button:
            text: "olá mundo 3"
            font_size: 30
            pos_hint: {'center_x': .5}
            size_hint: (.4, .2)