#:kivy 2.1.0

<MyGridLayout>
    GridLayout:
        cols: 1
        size: root.width, root.height
        GridLayout:
            cols: 2

            Label:
                text: "Login"
            TextInput:
                multiline: False

            Label:
                text: "Senha"
            TextInput:
                multiline: False

        Button:
            text: "Login"
            font_size: 40