<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10

        Label:
            text: "Name"
        
        TextInput:
            multiline: False

        Label:
            text: "Favorite pizza"
        
        TextInput:
            multiline: False

        Button:
            text:'Submit'
        
        Button:
            text:'Clear'